# NumPy Indexing and Selection

We will discuss how to select elements or groups of elements from an array.

In [0]:
import numpy as np

In [0]:
#Creating sample array
arr = np.arange(0,11)

In [0]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [0]:
#Get a value at an index
arr[8]

8

In [0]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [0]:
#Get values in a range
arr[0:7]

array([0, 1, 2, 3, 4, 5, 6])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [0]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [0]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [0]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [0]:
# Getting individual element value
arr_2d[1,0]

20

In [0]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [0]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [0]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [0]:
#Set up matrix
arr2d = np.zeros((10,10))

In [0]:
#Length of array
arr_length = arr2d.shape[1]

In [0]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [0]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [0]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [0]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [0]:
bool_arr = arr>4

In [0]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [0]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [0]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])